version: smartide/v0.2
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: boathouse-backend-dev
    webide-port: 6800
    ide-type: vscode
    volumes: 
      git-config: true
      ssh-key: true
  services:
    boathouse-backend-dev:
      container_name: boathouse-backend-dev
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-java-opvscode:latest
      restart: always
      environment:
        POSTGRES_HOST_AUTH_METHOD: trust
        ROOT_PASSWORD: root123
        TZ: Asia/Shanghai
      volumes:
        - $HOME/.m2/repository:/root/.m2/repository
        - .:/home/project
      expose:
        - 3000
        - 8100
        - 8101
      ports:
        - 8100:8100
        - 8101:8101
      networks:
        - boathouse-dev-network

    boathouse-backend-db:
      container_name: boathouse-backend-db
      image: registry.cn-hangzhou.aliyuncs.com/boathouse/mysql:5.6
      command: 
        - --default-authentication-plugin=mysql_native_password
      restart: always
      expose:
        - 3306
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: P2ssw0rd
      networks:
        - boathouse-dev-network

    phpmyadmin:
      container_name: phpmyadmin
      image: registry.cn-hangzhou.aliyuncs.com/boathouse/phpmyadmin:5.0.4-apache
      restart: always
      expose:
        - 8090
      ports:
        - 8090:80
      environment:
        PMA_ARBITRARY: "1"
      networks:
        - boathouse-dev-network
        
    jenkins:
      container_name: jenkins
      image: registry.cn-hangzhou.aliyuncs.com/boathouse/jenkins:lts
      user: root
      restart: always
      expose:
        - 8080
      ports:
        - '8080:8080'
        - '50000:50000'
      volumes:
        - '$HOME/jenkins_home:/var/jenkins_home'
      networks:
         - boathouse-dev-network

  networks:
    boathouse-dev-network:
      external: true
